imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "../../vendor/beberlei/DoctrineExtensions/config/mysql.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

monolog:
    channels: [ 'sword', 'lockss' ]
    handlers:
        lockss:
            level: notice
            type: rotating_file
            path: '%kernel.logs_dir%/lockss-%kernel.environment%.log'
            channels: [ lockss ]
            # max_files: 0
    handlers:
        sword:
            level: notice
            type: rotating_file
            path: '%kernel.logs_dir%/sword-%kernel.environment%.log'
            channels: [ sword ]
            # max_files: 0

framework:
    #esi: ~
    translator:
        enabled: true
        logging: false
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: PHP_SESSION_STAGE
        cookie_path: '%router.request_context.base_url%'
        cookie_domain: '%router.request_context.host%'
        cookie_secure: '%secure_cookies%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - '@NinesUtilBundle/Form/fields.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.root_dir%/../src/Nines/UtilBundle/Resources/views': NinesUtilBundle
        '%kernel.root_dir%/../src/AppBundle/Resources/views': ~
    exception_controller:  NinesUtilBundle:Error:showException
    date:
        format: D M j G:i:s T Y
        interval_format: '%%d days'

# Doctrine Configuration
doctrine:
    dbal:
        # default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: utf8mb4
                logging: false
                profiling: false
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

            oldversion:
                driver: pdo_mysql
                host: localhost
                port: ~
                dbname: pkppln
                user: pkppln
                password: abc123
                charset: utf8mb4
                logging: false
                profiling: false
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # bootstrapy pagination
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nines\UserBundle\Entity\User
    profile:
        form:
            type: Nines\UserBundle\Form\ProfileType
    change_password:
        form:
            type: Nines\UserBundle\Form\PasswordType
    from_email:
        address:        noreply@'%router.request_context.host%'
        sender_name:    Do Not Reply

nines_user:
    permission_levels: [ ROLE_ADMIN ]
