# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    container.autowiring.strict_mode: true

services:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Nines\UserBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: userNavMenu, alias: user}
            
    AppBundle\Services\:
        resource: '../../src/AppBundle/Services'
        public: true

    AppBundle\Services\FilePaths:
        public: true
        arguments:
            $root: '%pln.data_dir%'
            $projectDir: '%kernel.project_dir%'
            
    AppBundle\Services\Ping:
        arguments:
            $minOjsVersion: '%pln.min_ojs_version%'

    AppBundle\Services\Processing\Harvester:
        arguments: 
            $maxHarvestAttempts: '%pln.max_harvest_attepmts%'
